name: MybBlog web build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Upload to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: '${{ secrets.REMOTE_HOST }}'
          ssh_private_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          local_path: './dist/*'
          remote_path: ${{ secrets.REMOTE_PATH }}
